[fhe]
log_N = 16
scale_mod_size = 59
first_mod_size = 60
mult_depth = 10
log_batch_size = 15

secret_key_dist = "UNIFORM_TERNARY"
scaling_technique = "FIXEDMANUAL"
security_level = "HEStd_NotSet" # notset for resnet-34

level_budget = [4, 4]
