[fhe]
log_N = 6
scale_mod_size = 40
first_mod_size = 46
mult_depth = 10
log_batch_size = 5

secret_key_dist = "UNIFORM_TERNARY"
# scaling_technique = "FLEXIBLEAUTO"
# scaling_technique = "FIXEDMANUAL"
scaling_technique = "FLEXIBLEAUTO"
# security_level = "HEStd_128_classic"
security_level = "HEStd_NotSet"

level_budget = [3, 3]
